# Proyecto final

### Álvaro Andrés Esquivel Gómez  -  11002822




y = f(x) = mx +b

y = la variable dependiente
x = variable independiente
m = pendiente de la recta(parámetro del modelo)
b = intercepto(parámetro del modelo)

Tanto “x” como “y” son parte del dataset usado , “m” y “b” son parámetros del modelo los cuales **buscamos estimar con los datos**, esto significa que se busca encontrar que valores de “m” y “b” producen una recta que describa de la mejor manera posible la relación entre los datos “x” y “y”.


Por lo tanto en el proyecto:
y = el precio de venta real de cierta casa
x = cierta característica de cierta casa
yhat = f(x) = precio estimado o predicción del precio de venta para una casa con
cierta característica x
m = pendiente de la recta que usamos para aproximar el precio de la casa yhat
b = intercepto de la recta que usamos para aproximar el precio de la casa yhat

In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression

In [3]:
#Importando los datos
data = np.load("proyecto_training_data.npy")

print("Rango del tensor:",data.ndim) 
print("Forma o tamaño:",data.shape) 
print(data)
len_data = len(data)
print("\nCantidad de datos:",len_data)

Rango del tensor: 2
Forma o tamaño: (1460, 6)
[[2.08500e+05 7.00000e+00 8.56000e+02 8.00000e+00 2.00300e+03 6.50000e+01]
 [1.81500e+05 6.00000e+00 1.26200e+03 6.00000e+00 1.97600e+03 8.00000e+01]
 [2.23500e+05 7.00000e+00 9.20000e+02 6.00000e+00 2.00100e+03 6.80000e+01]
 ...
 [2.66500e+05 7.00000e+00 1.18800e+03 9.00000e+00 1.94100e+03 6.60000e+01]
 [1.42125e+05 5.00000e+00 1.07800e+03 5.00000e+00 1.95000e+03 6.80000e+01]
 [1.47500e+05 5.00000e+00 1.25600e+03 6.00000e+00 1.96500e+03 7.50000e+01]]

Cantidad de datos: 1460


In [ ]:
#Asignacion de variables de entrenamiento y de validacion usando sclicing
datos_entrenamiento = data[0:int(len_data*0.8)]


datos_validacion = data[int(len_data*0.8):len_data]


print("Datos entrenamiento: ", datos_entrenamiento, "\n\nlen datos_entrenamiento: ", len(datos_entrenamiento),
      "\n\nDatos validacion: ", datos_validacion, "\n\nlen datos_validacion: ", len(datos_validacion))

print("Forma datos_entrenamiento:",datos_entrenamiento.shape) 
print("Forma datos_entrenamiento:",datos_validacion.shape) 